name: Node app CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: MongoDB in Github Actions
              uses: supercharge/mongodb-github-action@1.3.0
            - name: Use Node.js
              uses: actions/setup-node@v1
            - run: npm install
            - run: npm test
            - uses: akhileshns/heroku-deploy@v3.8.8
              with:
                  heroku_api_key: ${{bf77addb-635e-4c3b-9558-c67823747ac8}}
                  heroku_app_name: "test-ci-cd-mehedi"
                  heroku_email: "mehedihassan2420@gmail.com"
